package vn.svframe.svframelib.skill.trigger;
import java.util.*; import java.util.concurrent.ConcurrentHashMap;
public class TriggerType {
 private static final Map<String,TriggerType> VALUES=new ConcurrentHashMap<>(); private final String name; private final boolean silent; private final boolean fromConfig;
 public static final TriggerType KILL_ENTITY=registerBuiltin("KILL_ENTITY"),KILL_PLAYER=registerBuiltin("KILL_PLAYER"),ATTACK=registerBuiltin("ATTACK"),DAMAGED=registerBuiltin("DAMAGED"),DAMAGED_BY_ENTITY=registerBuiltin("DAMAGED_BY_ENTITY"),DEATH=registerBuiltin("DEATH"),PLACE_BLOCK=registerBuiltin("PLACE_BLOCK"),BREAK_BLOCK=registerBuiltin("BREAK_BLOCK"),SHOOT_BOW=registerBuiltin("SHOOT_BOW"),ARROW_TICK=registerBuiltin("ARROW_TICK"),ARROW_HIT=registerBuiltin("ARROW_HIT"),ARROW_LAND=registerBuiltin("ARROW_LAND"),SHOOT_TRIDENT=registerBuiltin("SHOOT_TRIDENT"),TRIDENT_TICK=registerBuiltin("TRIDENT_TICK"),TRIDENT_HIT=registerBuiltin("TRIDENT_HIT"),TRIDENT_LAND=registerBuiltin("TRIDENT_LAND"),RIGHT_CLICK=registerBuiltin("RIGHT_CLICK"),LEFT_CLICK=registerBuiltin("LEFT_CLICK"),SHIFT_RIGHT_CLICK=registerBuiltin("SHIFT_RIGHT_CLICK"),SHIFT_LEFT_CLICK=registerBuiltin("SHIFT_LEFT_CLICK"),DROP_ITEM=registerBuiltin("DROP_ITEM"),SHIFT_DROP_ITEM=registerBuiltin("SHIFT_DROP_ITEM"),SWAP_ITEMS=registerBuiltin("SWAP_ITEMS"),SHIFT_SWAP_ITEMS=registerBuiltin("SHIFT_SWAP_ITEMS"),LOGIN=registerBuiltin("LOGIN"),SNEAK=registerBuiltin("SNEAK"),TELEPORT=registerBuiltin("TELEPORT"),TIMER=registerBuiltin("TIMER"),CAST=registerBuiltin("CAST"),COMMAND=registerBuiltin("COMMAND"),API=registerBuiltin("API"),EQUIP_ARMOR=registerBuiltin("EQUIP_ARMOR"),UNEQUIP_ARMOR=registerBuiltin("UNEQUIP_ARMOR"),PLUGIN=registerBuiltin("PLUGIN");
 public TriggerType(String name){this(name,false,false);} public TriggerType(String name,boolean silent){this(name,silent,false);} public TriggerType(String name,boolean silent,boolean fromConfig){this.name=norm(name);this.silent=silent;this.fromConfig=fromConfig;}
 private static TriggerType registerBuiltin(String id){TriggerType t=new TriggerType(id,false,false);VALUES.put(t.name,t);return t;} private static String norm(String s){return s==null?"":s.trim().toUpperCase(Locale.ROOT).replace('-','_').replace(' ','_');}
 public String name(){return name;} public boolean isSilent(){return silent;} public boolean isFromConfig(){return fromConfig;} public boolean isActionHandSpecific(){return name.contains("CLICK")||name.contains("DROP")||name.contains("SWAP");} public boolean isPassive(){return !Set.of("CAST","COMMAND","API","PLUGIN").contains(name);} public String getName(){return name;} public String getLowerCaseId(){return name.toLowerCase(Locale.ROOT);} public String toString(){return name;} public static TriggerType valueOf(String id){String n=norm(id);TriggerType t=VALUES.get(n);if(t==null)throw new IllegalArgumentException("Unknown trigger type "+id);return t;} public static void register(TriggerType t){VALUES.put(t.name,t);} public static void removeCustom(){VALUES.entrySet().removeIf(e->e.getValue().fromConfig);} public static Collection<TriggerType> values(){return List.copyOf(VALUES.values());} @Override public boolean equals(Object o){return o instanceof TriggerType t&&name.equals(t.name);}@Override public int hashCode(){return name.hashCode();}
}
