package vn.svframe.mythiclibfabric.runtime.script;
import java.util.*;
public final class ExpressionRuntime {
 public double evaluate(String expr,Map<String,Double> vars){return new Parser(substitute(expr,vars)).parseNumber();}
 public boolean evaluateBoolean(String expr,Map<String,Double> vars){return new Parser(substitute(expr,vars)).parseBoolean();}
 private static String substitute(String expr,Map<String,Double> vars){String s=expr==null?"0":expr.trim();if((s.startsWith("\"")&&s.endsWith("\""))||(s.startsWith("'")&&s.endsWith("'")))s=s.substring(1,s.length()-1);for(var e:vars.entrySet())s=s.replace("<"+e.getKey()+">",Double.toString(e.getValue()));s=s.replaceAll("<random\\.double>",Double.toString(Math.random()));return s;}
 private static final class Parser{final String s;int i;Parser(String s){this.s=s;}
  double parseNumber(){double v=add();skip();if(i!=s.length())throw new IllegalArgumentException("bad expression at "+i+" in "+s);return v;}
  boolean parseBoolean(){skip();int save=i;double a=add();skip();if(eat("=="))return a==add();if(eat("!="))return a!=add();if(eat(">="))return a>=add();if(eat("<="))return a<=add();if(eat(">"))return a>add();if(eat("<"))return a<add();skip();if(i==s.length())return a!=0;i=save;String w=word();if(w.equalsIgnoreCase("true"))return true;if(w.equalsIgnoreCase("false"))return false;throw new IllegalArgumentException("bad boolean "+s);}
  double add(){double v=mul();for(;;){skip();if(eat("+"))v+=mul();else if(eat("-"))v-=mul();else return v;}}
  double mul(){double v=pow();for(;;){skip();if(eat("*"))v*=pow();else if(eat("/"))v/=pow();else if(eat("%"))v%=pow();else return v;}}
  double pow(){double v=unary();skip();if(eat("^"))v=Math.pow(v,pow());return v;}
  double unary(){skip();if(eat("+"))return unary();if(eat("-"))return-unary();if(eat("(")){double v=add();if(!eat(")"))throw new IllegalArgumentException("missing )");return v;}if(i<s.length()&&(Character.isLetter(s.charAt(i))||s.charAt(i)=='_')){String fn=word().toLowerCase(Locale.ROOT);if(fn.equals("pi"))return Math.PI;if(fn.equals("e"))return Math.E;if(eat("(")){List<Double>a=new ArrayList<>();if(!peek(')')){do{a.add(add());}while(eat(","));}if(!eat(")"))throw new IllegalArgumentException("missing ) after "+fn);return function(fn,a);}throw new IllegalArgumentException("unknown symbol "+fn);}int st=i;while(i<s.length()&&(Character.isDigit(s.charAt(i))||s.charAt(i)=='.'||s.charAt(i)=='e'||s.charAt(i)=='E'||((s.charAt(i)=='+'||s.charAt(i)=='-')&&i>st&&(s.charAt(i-1)=='e'||s.charAt(i-1)=='E'))))i++;if(st==i)throw new IllegalArgumentException("number expected at "+i+" in "+s);return Double.parseDouble(s.substring(st,i));}
  double function(String f,List<Double>a){return switch(f){case"sin"->Math.sin(one(f,a));case"cos"->Math.cos(one(f,a));case"tan"->Math.tan(one(f,a));case"sqrt"->Math.sqrt(one(f,a));case"abs"->Math.abs(one(f,a));case"floor"->Math.floor(one(f,a));case"ceil"->Math.ceil(one(f,a));case"round"->Math.rint(one(f,a));case"min"->a.stream().mapToDouble(Double::doubleValue).min().orElseThrow();case"max"->a.stream().mapToDouble(Double::doubleValue).max().orElseThrow();case"non_zero"->a.isEmpty()?0:(Math.abs(a.get(0))<1e-12?(a.size()>1?a.get(1):1):a.get(0));case"clamp"->Math.max(a.get(1),Math.min(a.get(2),a.get(0)));default->throw new IllegalArgumentException("unknown function "+f);};}
  double one(String f,List<Double>a){if(a.size()!=1)throw new IllegalArgumentException(f+" expects 1 arg");return a.get(0);}String word(){skip();int st=i;while(i<s.length()&&(Character.isLetterOrDigit(s.charAt(i))||s.charAt(i)=='_'||s.charAt(i)=='.'))i++;return s.substring(st,i);}void skip(){while(i<s.length()&&Character.isWhitespace(s.charAt(i)))i++;}boolean eat(String x){skip();if(s.startsWith(x,i)){i+=x.length();return true;}return false;}boolean peek(char c){skip();return i<s.length()&&s.charAt(i)==c;}
 }
}
