package vn.svframe.svframemmo.manager;
import com.google.gson.*; import net.minecraft.server.MinecraftServer; import net.minecraft.server.network.ServerPlayerEntity; import net.minecraft.util.WorldSavePath; import vn.svframe.svframemmo.api.player.PlayerData;
import java.io.*;import java.nio.file.*;import java.util.*;import java.util.concurrent.*;
public final class PlayerDataManager {
 private final Map<UUID,PlayerData> data=new ConcurrentHashMap<>(); private final Gson gson=new GsonBuilder().setPrettyPrinting().create(); private Path file;
 public void start(MinecraftServer server){file=server.getSavePath(WorldSavePath.ROOT).resolve("svframemmo-playerdata.json");load(); for(ServerPlayerEntity p:server.getPlayerManager().getPlayerList())join(p);}
 public PlayerData join(ServerPlayerEntity p){PlayerData d=data.computeIfAbsent(p.getUuid(),PlayerData::blank);d.attach(p);return d;} public void quit(ServerPlayerEntity p){PlayerData d=data.get(p.getUuid());if(d!=null){d.detach();save();}}
 public PlayerData get(UUID id){return data.computeIfAbsent(id,PlayerData::blank);} public PlayerData get(ServerPlayerEntity p){return join(p);} public Collection<PlayerData> all(){return List.copyOf(data.values());}
 public synchronized void save(){if(file==null)return;try{Files.createDirectories(file.getParent());Map<String,Saved> out=new TreeMap<>();for(var e:data.entrySet()){PlayerData d=e.getValue();out.put(e.getKey().toString(),new Saved(d.getClassId(),d.getLevel(),d.getExperience(),d.getClassPoints(),d.getSkillPoints(),d.getAttributePoints(),d.getMana(),d.getStamina(),d.getStellium(),d.getAttributes()));}Path tmp=file.resolveSibling(file.getFileName()+".tmp");Files.writeString(tmp,gson.toJson(out));Files.move(tmp,file,StandardCopyOption.REPLACE_EXISTING,StandardCopyOption.ATOMIC_MOVE);}catch(Exception e){throw new IllegalStateException("Could not save SVFrameMMO player data",e);}}
 private synchronized void load(){data.clear();if(file==null||!Files.exists(file))return;try(Reader r=Files.newBufferedReader(file)){JsonObject root=JsonParser.parseReader(r).getAsJsonObject();for(var e:root.entrySet()){UUID id=UUID.fromString(e.getKey());Saved s=gson.fromJson(e.getValue(),Saved.class);PlayerData d=PlayerData.blank(id);d.restore(s.playerClass,s.level,s.experience,s.classPoints,s.skillPoints,s.attributePoints,s.mana,s.stamina,s.stellium,s.attributes);data.put(id,d);}}catch(Exception e){throw new IllegalStateException("Could not load SVFrameMMO player data",e);}}
 private record Saved(String playerClass,int level,double experience,int classPoints,int skillPoints,int attributePoints,double mana,double stamina,double stellium,Map<String,Double> attributes){}
}
