package vn.svframe.svframelib.damage;

import vn.svframe.svframelib.element.Element;
import java.util.*;

public class DamageMetadata implements Cloneable {
    public static final double MINIMAL_DAMAGE=0.001d;private final List<DamagePacket> packets=new ArrayList<>();private boolean weaponCrit,skillCrit;private final Set<Element> elementalCrits=new HashSet<>();
    public DamageMetadata(){}public DamageMetadata(double value,List<DamageType> types){this(new DamagePacket(value,types));}public DamageMetadata(double value,Element element,List<DamageType> types){this(new DamagePacket(value,element,types));}public DamageMetadata(DamagePacket initial){if(initial!=null)packets.add(initial);}public DamageMetadata(double value,DamageType...types){this(new DamagePacket(value,types));}public DamageMetadata(double value,Element element,DamageType...types){this(new DamagePacket(value,element,types));}
    public DamagePacket getInitialPacket(){return packets.isEmpty()?null:packets.get(0);}public double getDamage(){return packets.stream().mapToDouble(DamagePacket::getFinalValue).sum();}public double getDamage(Element e){return packets.stream().filter(p->Objects.equals(p.getElement(),e)).mapToDouble(DamagePacket::getFinalValue).sum();}public double getDamage(DamageType t){return packets.stream().filter(p->p.hasType(t)).mapToDouble(DamagePacket::getFinalValue).sum();}public List<DamagePacket> getPackets(){return List.copyOf(packets);}public Set<DamageType> collectTypes(){Set<DamageType>s=new LinkedHashSet<>();for(DamagePacket p:packets)s.addAll(p.getTypes());return s;}public Set<Element> collectElements(){Set<Element>s=new LinkedHashSet<>();for(DamagePacket p:packets)if(p.getElement()!=null)s.add(p.getElement());return s;}public Map<Element,Double> mapElementalDamage(){Map<Element,Double>m=new LinkedHashMap<>();for(DamagePacket p:packets)if(p.getElement()!=null)m.merge(p.getElement(),p.getFinalValue(),Double::sum);return m;}public boolean hasAnyType(List<DamageType>t){for(DamagePacket p:packets)if(p.hasAnyType(t))return true;return false;}public boolean hasType(DamageType t){for(DamagePacket p:packets)if(p.hasType(t))return true;return false;}public boolean hasElement(Element e){for(DamagePacket p:packets)if(Objects.equals(p.getElement(),e))return true;return false;}
    public DamageMetadata add(double value,DamageType...types){packets.add(new DamagePacket(value,types));return this;}public DamageMetadata add(double value,List<DamageType>types){packets.add(new DamagePacket(value,types));return this;}public DamageMetadata add(double value,Element e,DamageType...types){packets.add(new DamagePacket(value,e,types));return this;}public DamageMetadata add(double value,Element e,List<DamageType>types){packets.add(new DamagePacket(value,e,types));return this;}public DamageMetadata multiplicativeModifier(double m){packets.forEach(p->p.multiplicativeModifier(m));return this;}public DamageMetadata additiveModifier(double m){packets.forEach(p->p.additiveModifier(m));return this;}public DamageMetadata multiplicativeModifier(double m,DamageType t){packets.stream().filter(p->p.hasType(t)).forEach(p->p.multiplicativeModifier(m));return this;}public DamageMetadata multiplicativeModifier(double m,List<DamageType>t){packets.stream().filter(p->p.hasAnyType(t)).forEach(p->p.multiplicativeModifier(m));return this;}public DamageMetadata multiplicativeModifier(double m,Element e){packets.stream().filter(p->Objects.equals(p.getElement(),e)).forEach(p->p.multiplicativeModifier(m));return this;}public DamageMetadata additiveModifier(double m,DamageType t){packets.stream().filter(p->p.hasType(t)).forEach(p->p.additiveModifier(m));return this;}public DamageMetadata additiveModifier(double m,Element e){packets.stream().filter(p->Objects.equals(p.getElement(),e)).forEach(p->p.additiveModifier(m));return this;}
    public boolean isWeaponCriticalStrike(){return weaponCrit;}public void registerWeaponCriticalStrike(){weaponCrit=true;}public boolean isSkillCriticalStrike(){return skillCrit;}public void registerSkillCriticalStrike(){skillCrit=true;}public boolean isElementalCriticalStrike(Element e){return elementalCrits.contains(e);}public void registerElementalCriticalStrike(Element e){if(e!=null)elementalCrits.add(e);}public void registerCrits(List<String> ids){if(ids==null)return;for(String id:ids){if("weapon".equalsIgnoreCase(id))weaponCrit=true;else if("skill".equalsIgnoreCase(id))skillCrit=true;else try{elementalCrits.add(Element.valueOf(id));}catch(Exception ignored){}}}
    @Override public DamageMetadata clone(){DamageMetadata c=new DamageMetadata();for(DamagePacket p:packets)c.packets.add(p.clone());c.weaponCrit=weaponCrit;c.skillCrit=skillCrit;c.elementalCrits.addAll(elementalCrits);return c;}@Override public String toString(){return packets.toString();}
}
