package vn.svframe.svframelib.damage;

import vn.svframe.svframelib.element.Element;
import java.util.*;

public class DamagePacket implements Cloneable {
    private double value,additive,scalar=1d;private List<DamageType> types;private Element element;
    public DamagePacket(double value,List<DamageType> types){this(value,null,types);}public DamagePacket(double value,Element element,List<DamageType> types){if(!Double.isFinite(value)||value<0)throw new IllegalArgumentException("Value cannot be negative or non-finite");this.value=value;this.element=element;this.types=types==null?new ArrayList<>():new ArrayList<>(types);}public DamagePacket(double value,DamageType...types){this(value,null,types);}public DamagePacket(double value,Element element,DamageType...types){this(value,element,types==null?List.of():Arrays.asList(types));}
    public double getValue(){return value;}public List<DamageType> getTypes(){return types;}public Element getElement(){return element;}public void setTypes(List<DamageType> types){this.types=types==null?new ArrayList<>():new ArrayList<>(types);}public void setTypes(DamageType[] types){setTypes(types==null?List.of():Arrays.asList(types));}public void setValue(double value){if(!Double.isFinite(value)||value<0)throw new IllegalArgumentException("Value cannot be negative or non-finite");this.value=value;}public void setElement(Element element){this.element=element;}public void multiplicativeModifier(double modifier){if(!Double.isFinite(modifier))throw new IllegalArgumentException("modifier must be finite");scalar*=modifier;}public void additiveModifier(double modifier){if(!Double.isFinite(modifier))throw new IllegalArgumentException("modifier must be finite");additive+=modifier;}public double getFinalValue(){return value*Math.max(0d,1d+additive)*scalar;}public boolean hasType(DamageType type){return types.contains(type);}public boolean hasAnyType(List<DamageType> query){if(query==null)return false;for(DamageType t:query)if(types.contains(t))return true;return false;}@Override public DamagePacket clone(){DamagePacket c=new DamagePacket(value,element,types);c.additive=additive;c.scalar=scalar;return c;}@Override public String toString(){return "DamagePacket{value="+value+", types="+types+", element="+element+", additive="+additive+", scalar="+scalar+'}';}
}
